In [1]:
import numpy as np
import jieba

In [2]:
# 词表示方法 one_Hot方法

In [3]:
# 设置词典为

In [4]:
words_db = ["我们","又","爬山","跑步","去","一起","今天","昨天"]

In [5]:
# 词

In [6]:
word_one = "我们"

In [7]:
def getWord_vec(word,words_db):
    # 用一个词典长度的向量来表示这个词
    word_vec = np.zeros(len(words_db),dtype = "int32")
    for i in range(len(words_db)):
        if words_db[i] == word:
            word_vec[i] = 1
    return word_vec

In [8]:
getWord_vec(word_one,words_db)

array([1, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 句子表示

In [10]:
sentence_one = "我们今天去爬山"

In [11]:
sentence_array_one = list(jieba.cut(sentence_one,cut_all=False))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Lenovo\AppData\Local\Temp\jieba.cache
Loading model cost 0.752 seconds.
Prefix dict has been built successfully.


In [12]:
print("/".join(sentence_array_one))

我们/今天/去/爬山


In [13]:
# boolean方法

In [14]:
def getSentence_vec(sentence_array,words_db):
    # 用一个词典长度的向量来表示这个句子
    word_vec = np.zeros(len(words_db),dtype = "int32")
    for i in range(len(sentence_array)):
        for j in range(len(words_db)):
            if words_db[j] == sentence_array[i]:
                word_vec[j] = 1
                break
            
    return word_vec

In [15]:
getSentence_vec(sentence_array_one,words_db)

array([1, 0, 1, 0, 1, 0, 1, 0])

In [16]:
# count_boolean 方法表示句子

In [17]:
sentence_two = "我们今天又去爬山又去跑步"

In [18]:
sentence_array_two = list(jieba.cut(sentence_two,cut_all=False))
print("/".join(sentence_array_two))

我们/今天/又/去/爬山/又/去/跑步


In [19]:
def getSentence_vec_count(sentence_array,words_db):
        # 用一个词典长度的向量来表示这个句子
    word_vec = np.zeros(len(words_db),dtype = "int32")
    for i in range(len(sentence_array)):
        for j in range(len(words_db)):
            if words_db[j] == sentence_array[i]:
                word_vec[j] += 1
                break
            
    return word_vec

In [20]:
getSentence_vec_count(sentence_array_two,words_db)

array([1, 2, 1, 1, 2, 0, 1, 0])

In [21]:
# tf-idf 句子表示法

In [22]:
# tfidfw(S) = tf(count_vec)*idf(S)

In [23]:
# tf函数等同于count_boolean idf表示这个词在多少的文档中出现的占比倒数在求log ==>log(N/N(s)) N表示句子个数，N（S）表示出现S的句子个数

In [24]:
def getSentence_vec_tf_idf(sentence_array,words_db,sentences_db):
    word_vec = np.array(getSentence_vec_count(sentence_array,words_db)).astype(np.float32)
    nums = np.sum(sentences_db,axis=0)
    mothers = np.ones(len(sentences_db[0]))*len(sentences_db)
    print(word_vec)
    idf_vec = np.zeros(len(word_vec))
    for i in range(len(nums)):
        if(nums[i] != 0):
            idf_vec[i] = np.log2(mothers[i]/nums[i])
    word_vec = word_vec * idf_vec
    print(idf_vec)
    return word_vec

In [25]:
# 合并两个句子

In [26]:
vec_one = getSentence_vec(sentence_array_one,words_db)
vec_two = getSentence_vec(sentence_array_two,words_db)
sentences_db = np.vstack([vec_one,vec_two])
print(sentences_db)

[[1 0 1 0 1 0 1 0]
 [1 1 1 1 1 0 1 0]]


In [27]:
np.sum(sentences_db,axis=0)

array([2, 1, 2, 1, 2, 0, 2, 0])

In [28]:
getSentence_vec_tf_idf(sentence_array_one,words_db,sentences_db)

[1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0.])