In [1]:
import tensorflow as tf

In [2]:
# 直接使用线性模型

In [3]:
X = tf.ones([2,4])

In [4]:
W = tf.random.uniform([4,3],maxval=3,dtype=tf.float32)

In [13]:
b = tf.zeros([3])

In [8]:
Y =tf.constant([2,0]) # 该样例集有3个分类，分别是0，1，2 有两个样例集，输入为4个特征

In [14]:
with tf.GradientTape() as tape:
    tape.watch([W,b])
    prod = tf.math.softmax(X@W+b,axis=1)
    loss = tf.reduce_mean(tf.losses.MSE(tf.one_hot(Y,3),prod))
grad = tape.gradient(loss,[W,b])

In [15]:
grad

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[ 0.02871578,  0.0005672 , -0.02928299],
        [ 0.02871578,  0.0005672 , -0.02928299],
        [ 0.02871578,  0.0005672 , -0.02928299],
        [ 0.02871578,  0.0005672 , -0.02928299]], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.02871578,  0.0005672 , -0.02928299], dtype=float32)>]