In [3]:
import tensorflow as tf

In [6]:
w = tf.Variable(3.)

In [7]:
x = tf.Variable(3.)

In [8]:
b = tf.Variable(1.)

In [9]:
with tf.GradientTape() as tape:
    tape.watch([w])
    y = w*x+b
grad_w,grad_b = tape.gradient(y,[w,b])

In [10]:
grad_w,grad_b

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [11]:
# 连续求导

In [12]:
W = tf.Variable(1.)

In [13]:
X = tf.Variable(2.0)

In [14]:
B = tf.Variable(3.)

In [16]:
with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        Y = W*X+B
    grad_W,grad_B = t2.gradient(Y,[W,B])
grad_W_two = t1.gradient(grad_W,W)

In [20]:
print(grad_W_two)

None


In [21]:
# sigmoid函数梯度观察

In [22]:
a = tf.linspace(-10,10,10)

In [23]:
with tf.GradientTape() as tape:
    tape.watch([a])
    y = tf.sigmoid(a)
grad = tape.gradient(y,[a])

In [24]:
a,y,grad

(<tf.Tensor: shape=(10,), dtype=float64, numpy=
 array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
         -1.11111111,   1.11111111,   3.33333333,   5.55555556,
          7.77777778,  10.        ])>,
 <tf.Tensor: shape=(10,), dtype=float64, numpy=
 array([4.53978687e-05, 4.18766684e-04, 3.85103236e-03, 3.44451957e-02,
        2.47663801e-01, 7.52336199e-01, 9.65554804e-01, 9.96148968e-01,
        9.99581233e-01, 9.99954602e-01])>,
 [<tf.Tensor: shape=(10,), dtype=float64, numpy=
  array([4.53958077e-05, 4.18591319e-04, 3.83620191e-03, 3.32587242e-02,
         1.86326443e-01, 1.86326443e-01, 3.32587242e-02, 3.83620191e-03,
         4.18591319e-04, 4.53958077e-05])>])

In [2]:
# 上述证明 越靠近无穷，则梯度越平滑也就是越接近0

In [1]:
# tanh 函数介绍

In [4]:
a = tf.linspace(-1,1,10)

In [5]:
y = tf.tanh(a)

In [6]:
y

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([-0.76159416, -0.65142936, -0.5046724 , -0.32151274, -0.11065611,
        0.11065611,  0.32151274,  0.5046724 ,  0.65142936,  0.76159416])>

In [7]:
#  relu函数介绍

In [9]:
tf.nn.relu(a) # 显而易见

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.11111111, 0.33333333, 0.55555556, 0.77777778, 1.        ])>