In [1]:
import tensorflow as tf

In [2]:
with tf.device("gpu"):
    a = tf.range(10)

In [3]:
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [4]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [5]:
a.cpu()

Instructions for updating:
Use tf.identity instead.


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [6]:
tf.keras.layers

ModuleNotFoundError: No module named 'keras'

In [7]:
tf.keras

ModuleNotFoundError: No module named 'keras'

In [10]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.6.0 requires clang~=5.0, which is not installed.
tensorflow 2.6.0 requires flatbuffers~=1.12, but you have flatbuffers 20210226132247 which is incompatible.


In [11]:
tf.keras

ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (d:\Users\Lenovo\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\_api\v2\compat\v2\experimental\__init__.py)

In [12]:
avg = tf.random.normal([100,32,32,3])

In [13]:
avg = tf.fill([2,3],2.9)

In [14]:
avg

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.9, 2.9, 2.9],
       [2.9, 2.9, 2.9]], dtype=float32)>

In [15]:
a = 2

In [16]:
a.is_tensor()

AttributeError: 'int' object has no attribute 'is_tensor'

In [17]:
tf.is_tensor(a)

False

In [19]:
a =tf.constant(1.0,dtype=tf.int32)

TypeError: Cannot convert 1.0 to EagerTensor of dtype int32

In [ ]:
tf.