In [1]:
import tensorflow as tf 

In [4]:
# 定义神经网络层数

In [5]:
x = tf.random.uniform([4,3],maxval=10,dtype=tf.int32) # 4个样本，每个样本3维

In [6]:
net = tf.keras.layers.Dense(2) #变成 2维的网络 [b,N]==>[b,2] 这里就是[4,3] ==>[4,2]

In [7]:
out = net(x)

In [8]:
net.kernel.shape,net.bias.shape # kernel表示权重W矩阵 bias表示偏置B矩阵

(TensorShape([3, 2]), TensorShape([2]))

In [9]:
out.shape

TensorShape([4, 2])

In [10]:
out

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[12.037233  , -5.5500937 ],
       [ 5.472966  , -1.1209676 ],
       [ 9.721246  ,  0.31021625],
       [ 5.456813  , -0.5396297 ]], dtype=float32)>

In [11]:
x

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[4, 0, 8],
       [5, 3, 0],
       [0, 5, 9],
       [3, 3, 2]])>

In [12]:
# 将out 作0~1区间的转换

In [13]:
out = tf.math.softmax(out,axis=1)

In [15]:
out

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1.0000000e+00, 2.3010250e-08],
       [9.9863321e-01, 1.3667743e-03],
       [9.9991822e-01, 8.1809958e-05],
       [9.9751866e-01, 2.4814128e-03]], dtype=float32)>

In [16]:
# 取出最大值分类

In [17]:
out_index = tf.math.argmax(out,axis=1)

In [18]:
y = tf.random.uniform([4],maxval=2,dtype=tf.int32)

In [19]:
y

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 0, 1])>

In [27]:
out_index = tf.cast(out_index,dtype=tf.int32)

In [24]:
# 计算损失值

In [28]:
out_index.dtype,y.dtype

(tf.int32, tf.int32)

In [29]:
loss = tf.math.reduce_sum(tf.cast(tf.equal(out_index,y),dtype=tf.int32))

In [30]:
loss

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [31]:
# 求均值

In [32]:
loss_mean = loss/x.shape[0]

In [33]:
loss_mean

<tf.Tensor: shape=(), dtype=float64, numpy=0.25>