In [1]:
import tensorflow as tf

In [14]:
p_a = tf.constant([[0.1,0.2,0.7],
                  [0.9,0.05,0.05]])

In [15]:
p_a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.1 , 0.2 , 0.7 ],
       [0.9 , 0.05, 0.05]], dtype=float32)>

In [18]:
prev_index = tf.cast(tf.argmax(p_a,axis=1),dtype='int32') # 表示在列上（3个数中选最大的）选出最大值的下标并转换成int32

In [19]:
prev_index

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0])>

In [20]:
data_y = tf.constant([2,1],dtype='int32') # 表示真实数据为2类和1类

In [21]:
# 直接采用暴力的逻辑回归，即不相等就是0，相等就是1

In [22]:
correct = tf.cast(tf.equal(data_y,prev_index),dtype='int32')

In [23]:
correct # 对比值

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0])>

In [24]:
loss = tf.reduce_sum(correct) # 损失值

In [29]:
loss_mean = loss/len(correct) # 均值损失

In [30]:
loss_mean

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>